FROM mcr.microsoft.com/vscode/devcontainers/javascript-node:10

ARG USERNAME=node
ARG USER_UID=1000
ARG USER_GID=$USER_UID

RUN mkdir -p /ito-ocashi-review/node_modules
RUN mkdir -p /ito-ocashi-review/.next

